from telegram import (
    Update, InlineKeyboardButton, InlineKeyboardMarkup,
    ChatPermissions, InputMediaPhoto
)
import random
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler,
    MessageHandler, filters, ContextTypes
)
from pymongo import MongoClient
import logging
from telegram.ext import ApplicationBuilder
from telegram.ext import ChatMemberHandler

BOT_TOKEN = "8183522431:AAFqb8H5ZT5e-czF-bpCl12BEjVG9_cDW1g"
OWNER_ID = 6279412066
MONGO_URI = "mongodb+srv://wwwbangladeshiserverey:QLM2MQdEDFC4fsr2@miko.makogkx.mongodb.net/?retryWrites=true&w=majority&tls=true&appName=Miko"
LOG_GROUP_ID = -1002869505504  # Replace with your actual log group ID

client_db = MongoClient(MONGO_URI)
db = client_db["GroupBot"]
users_col = db["users"]
admins_col = db["admins"]
botdata = db["serena-bot"]
ratings_col = db["bot_ratings"]
ADMINS = [OWNER_ID]  # default
# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Test connection
menu_images = [
    "https://files.catbox.moe/eviz7e.jpg",
    "https://files.catbox.moe/tnjrqb.jpg",
    "https://files.catbox.moe/xycejx.jpg",
    "https://files.catbox.moe/jcjqhs.jpg",
    "https://files.catbox.moe/cidhop.jpg",
    "https://files.catbox.moe/qy1ti2.jpg",
    "https://files.catbox.moe/yriq4n.jpg"
]

truths = [
    "What’s your biggest fear?",
    "Have you ever lied to your best friend?",
    "What’s your weirdest habit?",
    "Have you ever cheated on a test?",
    "What’s the most embarrassing thing you’ve ever done?",
    "Who was your first crush?",
    "Have you ever stalked someone on social media?",
    "What’s one secret you’ve never told anyone?",
    "Do you sing in the shower?",
    "What’s your guilty pleasure song?",
    "Have you ever stolen anything?",
    "Have you ever had a crush on a teacher?",
    "What’s the worst date you’ve ever been on?",
    "What’s the most childish thing you still do?",
    "Have you ever told a big lie and gotten away with it?",
    "If you could swap lives with someone for a day, who would it be?",
    "Have you ever peed in a pool?",
    "What’s the last thing you searched for on Google?",
    "If you had to delete one app forever, which would it be?",
    "Who’s the last person you texted?",
    "What’s your biggest insecurity?",
    "Do you talk to yourself in the mirror?",
    "What’s something you wish you were better at?",
    "Have you ever blamed someone else for something you did?",
    "What’s your biggest regret?",
    "Have you ever had a crush on a friend's partner?",
    "What’s the dumbest thing you believed as a kid?",
    "If you were invisible, what’s the first thing you’d do?",
    "What’s your most useless talent?",
    "What’s the last lie you told?",
    "Who do you secretly envy and why?",
    "Have you ever broken something and not told anyone?",
    "Do you believe in ghosts?",
    "What’s something you’ve never told your parents?",
    "What’s your biggest relationship ick?",
    "Have you ever cried at a movie?",
    "What’s your most awkward moment?",
    "If you had to date a cartoon character, who would it be?",
    "What’s your worst habit?",
    "What’s your most irrational fear?",
    "Have you ever pretended to be sick to get out of something?",
    "If you had to delete all but three apps, which ones would you keep?",
    "What’s the worst gift you’ve ever received?",
    "What’s something illegal you’ve done?",
    "What’s the weirdest thing you’ve eaten?",
    "Have you ever farted and blamed someone else?",
    "What’s your most cringe memory?",
    "What would you do if you switched gender for a day?",
    "Have you ever ghosted someone?",
    "What’s something you wish people knew about you?",
    "Do you keep a secret diary or notes?",
    "What’s your biggest dealbreaker in a relationship?",
    "What do you pretend to know more about than you really do?",
    "Have you ever lied during a truth or dare game?",
    "Who do you think is the best-looking person in this group?",
    "What would you do if you won the lottery?",
    "What’s the most romantic thing someone has done for you?",
    "Do you have any weird phobias?",
    "What’s your wildest dream?",
    "What’s the worst trouble you’ve ever gotten into?",
    "What’s the most random fact you know?"
]

dares = [
    "Sing your favorite song",
    "Do 10 push-ups",
    "Send a funny sticker",
    "Dance for 30 seconds without music",
    "Talk in an accent for 5 minutes",
    "Post a silly selfie to your story",
    "Say the alphabet backwards",
    "Eat a spoonful of ketchup",
    "Imitate your favorite celebrity",
    "Send a voice note of you laughing like a villain",
    "Do your best chicken dance",
    "Pretend to be a dog for 1 minute",
    "Call someone and say you love pineapples",
    "Do 15 jumping jacks",
    "Draw a mustache on your face and keep it for 10 minutes",
    "Act like a monkey until your next turn",
    "Try to touch your nose with your tongue",
    "Text your crush 'I like you' (then delete if needed)",
    "Do a handstand or try",
    "Try to lick your elbow",
    "Speak without moving your lips for 2 minutes",
    "Show the last photo in your gallery",
    "Eat something spicy right now",
    "Talk in gibberish for the next round",
    "Draw a portrait of someone using your non-dominant hand",
    "Imitate someone in the group",
    "Try to juggle 3 things",
    "Balance something on your head for 1 minute",
    "Do your best robot dance",
    "Give yourself a weird nickname and use it for the next hour",
    "Write a poem on the spot and recite it",
    "Change your profile pic to something funny for 5 minutes",
    "Type with your toes and send the result",
    "Say a tongue twister 5 times fast",
    "Do 20 squats",
    "Pretend you’re underwater for 1 minute",
    "Make a funny face and keep it for 30 seconds",
    "Speak like Yoda for 3 minutes",
    "Try to do a magic trick",
    "Talk using only emojis for one round",
    "Post “I believe in aliens” on your status",
    "Do a cartwheel or roll on the floor",
    "Wrap yourself in a blanket and pretend to be a burrito",
    "Try to whistle with a mouthful of water",
    "Make a hat out of paper and wear it",
    "Put 5 ice cubes down your shirt",
    "Draw a tattoo on your arm with pen",
    "Pretend to cry like a baby for 1 minute",
    "Act like your phone is a baby and sing it a lullaby",
    "Speak like a robot for the next 5 minutes",
    "Do a silly walk across the room",
    "Try to breakdance for 10 seconds",
    "Try to moonwalk",
    "Hold your breath for 20 seconds",
    "Wear socks on your hands for 5 minutes",
    "Act like a zombie and scare someone",
    "Pretend you’re a famous actor giving a speech",
    "Spin around 10 times and try to walk straight",
    "Do the floss dance for 30 seconds"
]

compliments = [
    "You have an incredible sense of humor!",
    "Your determination is inspiring.",
    "You have a talent for making people feel at ease.",
    "You are a beacon of hope and positivity.",
    "Your intelligence shines through in everything you do.",
    "You have a heart that understands others.",
    "Your presence is a gift to everyone around you.",
    "You are a wonderful friend.",
    "Your passion is contagious!",
    "You have a way of making people feel valued.",
    "You are a true original, and that's what makes you special.",
    "Your enthusiasm is refreshing.",
    "You handle challenges with such grace.",
    "You have an eye for beauty in the world.",
    "Your support means the world to me.",
    "You make every day brighter just by being you.",
    "Your insights are always so valuable.",
    "You bring joy to those around you.",
    "You have a great sense of style!",
    "Your courage is truly commendable.",
    "You radiate positivity.",
    "Your creativity knows no bounds.",
    "You have a unique perspective on life.",
    "Your kindness is a balm to everyone who encounters it.",
    "You inspire others to be their best selves.",
    "Your smile lights up the room.",
    "You are an amazing listener.",
    "Your enthusiasm is infectious.",
    "You have a beautiful soul.",
    "Your energy is uplifting.",
    "You make the world a better place just by being in it.",
    "You have a gift for bringing people together.",
    "Your laughter is music to my ears.",
    "You are so talented!",
    "Your ability to see the good in people is admirable.",
    "You have a wonderful way with words.",
    "Your strength is admirable.",
    "You are full of wisdom beyond your years.",
    "Your compassion is unmatched.",
    "You have a great sense of adventure!",
    "Your determination is inspiring to others.",
    "You are an invaluable part of this team.",
    "Your optimism is refreshing.",
    "You have a magnetic personality!",
    "Your attention to detail is impressive.",
    "You are so thoughtful and considerate.",
    "Your authenticity is refreshing.",
    "You have a way of making everything better.",
    "Your smile can brighten the darkest day.",
    "You are a ray of sunshine on a cloudy day.",
    "Your zest for life is contagious!",
    "You have such a warm and welcoming spirit.",
    "Your intelligence is truly impressive.",
    "You bring out the best in others.",
    "Your perspective is always enlightening.",
    "You have an incredible work ethic.",
    "You are so resourceful!",
    "Your laughter brings joy to those around you.",
    "You have such a positive influence on those around you.",
    "Your ability to connect with others is remarkable.",
    "You have an amazing ability to adapt to any situation.",
    "Your generosity knows no bounds.",
    "You are such a great problem solver!",
    "Your passion for your interests is inspiring.",
    "You make even the mundane seem exciting!",
    "Your insights always make me think deeper.",
    "You are incredibly empathetic.",
    "Your friendship is one of my greatest treasures.",
    "You are always willing to lend a hand.",
    "Your love for learning is admirable.",
    "You have a knack for making people feel special.",
    "Your resilience is truly inspiring.",
    "You have an extraordinary ability to make others laugh.",
    "Your presence brings peace to those around you.",
    "You are so dependable and trustworthy.",
    "Your curiosity about the world is refreshing.",
    "You possess such grace under pressure.",
    "Your ideas are always innovative and fresh!",
    "You have an amazing ability to uplift others' spirits.",
    "Your thoughtfulness is a rare quality.",
    "You're an incredible communicator!",
    "Your kindness leaves a lasting impression on everyone you meet.",
    "You have a beautiful way of expressing yourself.",
    "Your laughter can light up any room!",
    "You're an inspiration to everyone around you!",
    "You're so easy to talk to; I appreciate that about you!",
    "You're like a breath of fresh air!",
]

roasts = [
    "You're the reason the gene pool needs a lifeguard.",
    "You bring everyone so much joy… when you leave the room.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'd agree with you, but then we'd both be wrong.",
    "You're proof that even evolution makes mistakes.",
    "You're like a software update. Whenever I see you, I think, 'Not now.'",
    "You have the right to remain silent because whatever you say will probably be stupid anyway.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're as useless as the 'ueue' in 'queue.'",
    "I’d explain it to you, but I left my English-to-Dingbat dictionary at home.",
    "You’re not stupid; you just have bad luck when it comes to thinking.",
    "You're like a candle in the wind—useless and annoying.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "I’d call you a tool, but that implies you’re actually useful.",
    "You're about as useful as a screen door on a submarine.",
    "You have an entire life to be an idiot. Why not take today off?",
    "You're like a software license agreement. Everyone just ignores you.",
    "You're like a broken pencil—pointless.",
    "I'd explain it to you, but I don't have any crayons.",
    "You're so dense, light bends around you.",
    "I’d ask how old you are, but I know you can’t count that high.",
    "You're like a slinky; not really good for anything, but you bring a smile when you fall down the stairs.",
    "You’re like a light switch; even when you’re on, you’re still dim.",
    "You bring everyone so much joy… when you leave the room.",
    "You're like a software bug—nobody wants you around.",
    "If I had a dollar for every time I saw someone as dumb as you, I’d have one dollar.",
    "Your face makes onions cry.",
    "You're the reason God created the middle finger.",
    "You're like a dictionary—full of useless information.",
    "I'd call you a tool, but that implies you're actually useful.",
    "Your only chance of getting laid is by crawling up a chicken's butt and waiting.",
    "You're proof that even evolution makes mistakes.",
    "You're like a black hole; you suck all the fun out of the room.",
    "I would call you a joke, but that would imply you're funny.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'd explain it to you, but I don't have any crayons.",
    "You’re so full of it, even your shadow leaves you.",
    "You bring everyone so much joy... when you leave the room.",
    "You're about as useful as a chocolate teapot.",
    "I'd give you a nasty look, but you've already got one.",
    "You're like a software update. Whenever I see you, I think, 'Not now.'",
    "You’re like a broken pencil—pointless.",
    "If ignorance is bliss, you must be the happiest person on the planet.",
    "You're not stupid; you just have bad luck when it comes to thinking.",
    "You're like a candle in the wind—useless and annoying.",
    "You have an entire life to be an idiot. Why not take today off?",
    "If brains were dynamite, you wouldn't have enough to blow your nose.",
    "You're so dense, light bends around you.",
    "I’d ask how old you are, but I know you can’t count that high.",
    "You're about as useful as a screen door on a submarine.",
    "You're like a software bug—nobody wants you around.",
    "I'd call you a tool, but that implies you're actually useful.",
    "You bring everyone so much joy… when you leave the room.",
    "You’re like a slinky; not really good for anything, but you bring a smile when you fall down the stairs.",
    "Your face makes onions cry.",
    "You’re proof that even evolution makes mistakes.",
    "I'd explain it to you, but I left my English-to-Dingbat dictionary at home.",
    "You're like a black hole; you suck all the fun out of the room.",
    "I would call you a joke, but that would imply you're funny.",
    "You're so full of it, even your shadow leaves you.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You’re as useless as the 'ueue' in 'queue.'",
    "I’d give you a nasty look, but you've already got one.",
    "You have an entire life to be an idiot. Why not take today off?",
]

jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "I told my computer I needed a break, and it said 'No problem – I'll go to sleep.'",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the math book look sad? Because it had too many problems.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why can't you give Elsa a balloon? Because she will let it go!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How does a scientist freshen her breath? With experi-mints!",
    "What did one wall say to the other wall? 'I'll meet you at the corner!'",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "What do you call a lazy kangaroo? A pouch potato!",
    "Why was the math book sad? Because it had too many problems.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the picture go to jail? Because it was framed!",
    "How do you organize a space party? You planet!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did the janitor say when he jumped out of the closet? 'Supplies!'",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "What did one hat say to the other hat? 'You stay here, I'll go on ahead!'",
    "Why did the computer go to therapy? It had too many bytes.",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "What do you call an alligator in a vest? An investigator!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "How does a penguin build its house? Igloos it together!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "How does a scientist freshen her breath? With experi-mints!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long.",
    "What do you call an alligator in a vest? An investigator!",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why did the mushroom go to the party alone? Because he’s a fungi!",
    "What do you get when you cross a snowman with a dog? Frostbite.",
    "Why was the computer cold? It left its Windows open!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "How does a scientist freshen her breath? With experi-mints!",
    "What do you call an elephant that doesn’t matter? An irrelephant.",
    "Why did the man put his money in the blender? Because he wanted to make some liquid assets!",
    "Why was the broom late? It swept in.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "How does Moses make his coffee? Hebrews it.",
    "What’s brown and sticky? A stick.",
]

personalities = [
    "Kind", "Funny", "Rude", "Caring", "Introvert", "Extrovert", "Creative", 
    "Lazy", "Hardworking", "Bold", "Adventurous", "Tho